site_name: perfect-strangers
repo_url: https://github.com/seanlikeskites/perfect-strangers
copyright: "Copyright &copy; 2026 Sean Enderby"

watch:
  - docs/scripts/main.py
  - src

extra:
  generator: false

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
  
extra_javascript:
  - javascript/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

nav:
  - Home: index.md
  - Usage:
    - usage/quick_start.md
    - usage/matcher_objects.md
    - usage/license.md
  - Theory:
    - theory/overview.md
    - theory/round_robin.md
#    - theory/kirkman.md


theme:
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    scheme: default

markdown_extensions:
  - attr_list
  - pymdownx.blocks.caption
  - markdown.extensions.smarty
  - zensical.extensions.macros:
      module_name: docs/scripts/main
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_source: false

