site_name: perfect-strangers
repo_url: https://github.com/seanlikeskites/perfect-strangers
copyright: "Copyright &copy; 2026 Sean Enderby"

extra:
  generator: false

nav:
  - Home: index.md
  - Usage:
    - usage/quick_start.md
    - usage/matcher_objects.md
#  - Theory:
#    - theory/overview.md
#    - theory/kirkman.md


theme:
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    scheme: default

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_source: false
