name: Publish
on:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write
jobs:
  deploy:
    environment:
      name: pypi
      url: https://pypi.org/project/perfect-strangers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install hatch
      - run: hatch build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
