name: Run Tests
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  test:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install hatch
      - run: hatch test --all
